FROM nginx
MAINTAINER Austin Flores <me@austinflores.com>

RUN rm -rf /usr/share/nginx/html/*

# Not currently using public
#COPY public /usr/share/nginx/html

COPY etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir /etc/nginx/ssl

COPY etc/nginx/ssl/nginx.crt /etc/nginx/ssl/nginx.crt
COPY etc/nginx/ssl/nginx.key /etc/nginx/ssl/nginx.key
